language: java
jdk:
 - openjdk11
addons:
  sonarcloud:
    organization: "pepstock-org"
    token: ${SONAR_TOKEN}
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - Dsonar.projectKey=UnimibSoftEngCourse2021_travis-exercise-giobrus
